spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/carlos?serverTimezone=UTC
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        